### ISSUE TITLE
DbInstance Stuck Creating

### ISSUE THREAD

**Issue by Newman-Hui** [db-operator/charts#58]
Hi, I'm using db operator to try and connect to a cnpg cluster, and the dbinstance is stuck in creating. The cnpg cluster is available on a service, and the secret I'm using to attempt to connect is the super user that cnpg operator creates. The logging only says "generic is not implimented yet" but during testing I'm positive I was able to create a dbinstance and create a database object. Can someone give me some debugging advice, as the logs and the documentation isn't super helpful here. Maybe important to note that I disabled the webhook creation, due to some helmrelease upgrade failures, and I didn't think it was necessary, but maybe I'm wrong. 

db-operator v2.6.1 
Helm chart version 1.25.0

**Comment by allanger** [comment]
Hi, Webhook is optional, so it's not a problem. 

We're migrating from one logger to another, so currently logs might be messy, I'll try taking care of it within the next couple of weeks. 

If db-operator says that generic is not implemented, it means that it couldn't connect to a dbin and hence it assumes that a server should be created. But since creation is not supported for generic instances, it's throwing this error. 

I think that a good first step would be to check the secret that is used by db-operator to connect to the instance, and try connecting using with the same creds using psql.

If it works, you can also create a pod with psql in the same cluster and check whether it's possible to connect from the cluster

**Comment by Newman-Hui** [comment]
Hmm, already tried connecting manually with the credentials and I didn't run into any issues there. Could it be a namespacing issue? db-operator is in one namespace and the cluster being connected to is in another. I know dbinstances are cluster scoped, but does it have some kind of sanity checker with the db-operator?

**Comment by allanger** [comment]
If the database service is available from the namespace where the db-operator is deployed, there must be no problems. 

So it's either you have some  network policies in the cluster that won't let the traffic through. But usually it's the problem with the hostname that is set for the dbinsntance, would you mind sharing the hostname you've set?

**Comment by Newman-Hui** [comment]
Spec:
  Generic:
    Host:  {service-name}.{namespace}.svc.cluster.local
    Port:  5432

I've replaced the service name and the namespace it's residing in. In the meantime I'll double check the network policies

**Comment by allanger** [comment]
The easiest way you can check is just by creating a pod with psql in the same ns as the operator is deployed, mounting the secret and configmap to that pod, and trying connecting using data directly from mounts

**Comment by allanger** [comment]
@Newman-Hui Were you able to get it working? I would like to close the issue

**Comment by allanger** [comment]
I've also accidentally found out, that this error is also returned, when the admin password is not correct. I'll try making errors more clear

**Comment by Newman-Hui** [comment]
Sorry for the delayed response. Yes, we found out it was a calico network policy, preventing the dboperator from accessing the cluster in another namespace.

**Comment by allanger** [comment]
I would ask you to open an issue in the main project repo next time, it would be easier for us to track it there.

Here: https://github.com/db-operator/db-operator/
